#!/usr/bin/env python3
"""Rasterize the demo's four faces into CM7/Core/Inc/fonts.h as 2-bit (4-level)
anti-aliased glyph atlases, ASCII 32..126, proportional advances.

Faces (all Bitstream Vera / DejaVu licence, which permits embedding the
rendered bitmaps): DejaVu Sans Mono 16 px for every text line, DejaVu Sans
Condensed (with a 1 px stroke for weight) at 24 px (step strip), 32 px (lane names) and 40 px (the four
numbers per lane). Each glyph is stored as rows of 2-bit alpha, MSB first; the
firmware composites fg over the known background colour in software, so a
glyph is one store per pixel and never reads the framebuffer.

    python3 tools/gen_fonts.py   (needs Pillow with FreeType)
"""
import pathlib, sys
from PIL import Image, ImageDraw, ImageFont

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parents[0] / "CM7" / "Core" / "Inc" / "fonts.h"
MPL = pathlib.Path("/opt/homebrew/anaconda3/lib")
def find(name):
    for base in [pathlib.Path.home() / "Library/Fonts", *MPL.glob("python3*/site-packages/matplotlib/mpl-data/fonts/ttf")]:
        p = base / name
        if p.exists(): return p
    sys.exit(f"font not found: {name}")

FACES = [  # (c name, file, px size, cell height, stroke width for weight)
    ("mono16", "DejaVuSansMono.ttf", 15, 18, 0),
    ("cond24", "DejaVuSansCondensed.ttf", 22, 26, 1),
    ("cond32", "DejaVuSansCondensed.ttf", 30, 34, 1),
    ("cond40", "DejaVuSansCondensed.ttf", 38, 42, 1),
]
lines = ["/* Generated by tools/gen_fonts.py from DejaVu Sans Mono and DejaVu Sans Condensed Bold",
         " * (Bitstream Vera licence). 2-bit alpha glyphs, MSB first, rows of ceil(w/4) bytes. Do not edit. */",
         "#ifndef FONTS_H", "#define FONTS_H", "#include <stdint.h>",
         "typedef struct { uint8_t w, adv; int8_t dx; uint16_t off; } glyph_t;",
         "typedef struct { const uint8_t *bits; const glyph_t *g; uint8_t h; uint8_t base; } font_t;"]
total = 0
for cname, file, px, cell, sw in FACES:
    font = ImageFont.truetype(str(find(file)), px)
    ascent, descent = font.getmetrics()
    base = min(cell - 1, ascent)                      # baseline row inside the cell
    bits, glyphs = [], []
    for code in range(32, 127):
        ch = chr(code)
        l, t, r, b = font.getbbox(ch, stroke_width=sw)
        adv = int(round(font.getlength(ch))) + sw
        w = max(0, r - l)
        im = Image.new("L", (max(w, 1), cell), 0)
        ImageDraw.Draw(im).text((-l, base - ascent), ch, font=font, fill=255, stroke_width=sw, stroke_fill=255)
        rowbytes = (w + 3) // 4
        off = len(bits)
        for y in range(cell):
            acc = 0
            for x in range(rowbytes * 4):
                v = im.getpixel((x, y)) if x < w else 0
                acc = (acc << 2) | (v >> 6)
            bits += [(acc >> (8 * (rowbytes - 1 - i))) & 0xFF for i in range(rowbytes)]
        glyphs.append((w, adv, l, off))
    total += len(bits)
    lines.append(f"static const uint8_t {cname}_bits[{len(bits)}] = {{")
    for i in range(0, len(bits), 24):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in bits[i:i+24]) + ",")
    lines.append("};")
    lines.append(f"static const glyph_t {cname}_glyphs[95] = {{")
    for (w, adv, dx, off), code in zip(glyphs, range(32, 127)):
        label = "backslash" if code == 92 else chr(code)
        lines.append(f"    {{{w}, {adv}, {dx}, {off}}}, /* '{label}' */")
    lines.append("};")
    lines.append(f"static const font_t {cname} = {{ {cname}_bits, {cname}_glyphs, {cell}, {base} }};")
lines += ["#endif", ""]
OUT.write_text("\n".join(lines))
print(f"{OUT} written; {total} bytes of glyph data")
