#!/usr/bin/env python3
"""Rasterize a 16-px monospace cell font into CM7/Core/Inc/font16.h.

Uses Pillow's bundled default face (Aileron, CC0) so the glyph bitmaps can be
committed without a licence question. Output: `font16[95][16]`, one uint16_t
row mask per glyph row, MSB = leftmost pixel, cell 10x16, ASCII 32..126.
"""
import pathlib, sys
from PIL import Image, ImageDraw, ImageFont

CELL_W, CELL_H = 10, 16
out = pathlib.Path(__file__).resolve().parents[1] / "CM7" / "Core" / "Inc" / "font16.h"
font = ImageFont.load_default(size=14)
rows = []
for code in range(32, 127):
    im = Image.new("L", (CELL_W, CELL_H), 0)
    d = ImageDraw.Draw(im)
    ch = chr(code)
    bbox = d.textbbox((0, 0), ch, font=font)
    w = bbox[2] - bbox[0]
    x = (CELL_W - w) // 2 - bbox[0]
    d.text((x, -1), ch, font=font, fill=255)
    masks = []
    for y in range(CELL_H):
        m = 0
        for xx in range(CELL_W):
            if im.getpixel((xx, y)) > 96:
                m |= 1 << (15 - xx)
        masks.append(m)
    rows.append((code, masks))
lines = ["/* Generated by tools/gen_font.py from Pillow's bundled Aileron face (CC0). Do not edit. */",
         "#ifndef FONT16_H", "#define FONT16_H", "#include <stdint.h>",
         f"#define FONT_W {CELL_W}u", f"#define FONT_H {CELL_H}u",
         "static const uint16_t font16[95][16] = {"]
for code, masks in rows:
    label = "backslash" if chr(code) == "\\" else chr(code)
    lines.append("    {" + ", ".join(f"0x{m:04x}" for m in masks) + "}, /* '" + label + "' */")
lines += ["};", "#endif", ""]
out.write_text("\n".join(lines))
print(out, "written;", len(rows), "glyphs; pillow", __import__("PIL").__version__)
