"""Type stubs for expanse-trie Python bindings."""

from typing import (
    Any,
    Callable,
    Dict,
    Iterable,
    Iterator,
    List,
    Optional,
    Tuple,
    Union,
    overload,
)

__version__: str

# String-map keys round-trip as `str` when the key bytes are valid UTF-8, or as
# `bytes` when they are not (a lossy decode would mangle non-UTF-8 keys).
StrKey = Union[str, bytes]

class ExpanseSet:
    """Sparse, dynamic 64-bit integer set (Judy1 equivalent)."""

    def __init__(self, iterable: Optional[Iterable[int]] = None) -> None: ...
    def insert(self, key: int) -> bool: ...
    def add(self, key: int) -> bool: ...
    def remove(self, key: int) -> bool: ...
    def discard(self, key: int) -> bool: ...
    def pop(self) -> int: ...
    def contains(self, key: int) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    @property
    def empty(self) -> bool: ...
    def mem_used(self) -> int: ...
    def total_node_allocs(self) -> int: ...
    def clear(self) -> None: ...
    def first(self) -> Optional[int]: ...
    def last(self) -> Optional[int]: ...
    def next(self, key: int, inclusive: bool = False) -> Optional[int]: ...
    def next_at_or_after(self, key: int) -> Optional[int]: ...
    def next_after(self, key: int) -> Optional[int]: ...
    def prev(self, key: int, inclusive: bool = False) -> Optional[int]: ...
    def prev_at_or_before(self, key: int) -> Optional[int]: ...
    def prev_before(self, key: int) -> Optional[int]: ...
    def count_below(self, key: int) -> int: ...
    def count_range(self, start: int, end: int) -> int: ...
    def by_count(self, index: int) -> Optional[int]: ...
    def range(
        self,
        start: Optional[int] = None,
        end: Optional[int] = None,
        inclusive: bool = True,
    ) -> List[int]: ...
    def to_list(self) -> List[int]: ...
    def update(self, other: Iterable[int]) -> None: ...
    def insert_many(self, keys: Any) -> int: ...
    def __contains__(self, key: int) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    def __repr__(self) -> str: ...

class ExpanseMap:
    """Sparse, dynamic 64-bit integer-to-integer map (JudyL equivalent)."""

    def __init__(
        self, items: Optional[Union[Dict[int, int], Iterable[Tuple[int, int]]]] = None
    ) -> None: ...
    def insert(self, key: int, val: int) -> Optional[int]: ...
    @overload
    def get(self, key: int) -> Optional[int]: ...
    @overload
    def get(self, key: int, default: int) -> int: ...
    def get(self, key: int, default: Optional[int] = None) -> Optional[int]: ...
    def remove(self, key: int) -> Optional[int]: ...
    @overload
    def pop(self, key: int) -> int: ...
    @overload
    def pop(self, key: int, default: int) -> int: ...
    def pop(self, key: int, default: Optional[int] = None) -> Optional[int]: ...
    def contains_key(self, key: int) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    @property
    def empty(self) -> bool: ...
    def mem_used(self) -> int: ...
    def total_node_allocs(self) -> int: ...
    def clear(self) -> None: ...
    def first(self) -> Optional[Tuple[int, int]]: ...
    def last(self) -> Optional[Tuple[int, int]]: ...
    def next(self, key: int, inclusive: bool = False) -> Optional[Tuple[int, int]]: ...
    def next_at_or_after(self, key: int) -> Optional[Tuple[int, int]]: ...
    def next_after(self, key: int) -> Optional[Tuple[int, int]]: ...
    def prev(self, key: int, inclusive: bool = False) -> Optional[Tuple[int, int]]: ...
    def prev_at_or_before(self, key: int) -> Optional[Tuple[int, int]]: ...
    def prev_before(self, key: int) -> Optional[Tuple[int, int]]: ...
    def count_below(self, key: int) -> int: ...
    def count_range(self, start: int, end: int) -> int: ...
    def by_count(self, index: int) -> Optional[Tuple[int, int]]: ...
    def range(
        self,
        start: Optional[int] = None,
        end: Optional[int] = None,
        inclusive: bool = True,
    ) -> List[Tuple[int, int]]: ...
    def to_list(self) -> List[Tuple[int, int]]: ...
    def keys(self) -> List[int]: ...
    def values(self) -> List[int]: ...
    def items(self) -> List[Tuple[int, int]]: ...
    def update(self, other: Any) -> None: ...
    def insert_many(self, keys: Any, values: Any) -> int: ...
    def __getitem__(self, key: int) -> int: ...
    def __setitem__(self, key: int, val: int) -> None: ...
    def __delitem__(self, key: int) -> None: ...
    def __contains__(self, key: int) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    def __repr__(self) -> str: ...

class ExpanseStrMap:
    """Variable-length string/bytes-to-integer trie map (JudySL equivalent).

    Keys are returned as ``str`` when their bytes are valid UTF-8, otherwise as
    ``bytes`` — non-UTF-8 keys round-trip losslessly.
    """

    def __init__(self) -> None: ...
    def insert(self, key: StrKey, val: int) -> Optional[int]: ...
    @overload
    def get(self, key: StrKey) -> Optional[int]: ...
    @overload
    def get(self, key: StrKey, default: int) -> int: ...
    def get(self, key: StrKey, default: Optional[int] = None) -> Optional[int]: ...
    def remove(self, key: StrKey) -> Optional[int]: ...
    @overload
    def pop(self, key: StrKey) -> int: ...
    @overload
    def pop(self, key: StrKey, default: int) -> int: ...
    def pop(self, key: StrKey, default: Optional[int] = None) -> Optional[int]: ...
    def contains_key(self, key: StrKey) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    @property
    def empty(self) -> bool: ...
    def mem_used(self) -> int: ...
    def clear(self) -> None: ...
    def first(self) -> Optional[Tuple[StrKey, int]]: ...
    def last(self) -> Optional[Tuple[StrKey, int]]: ...
    def next(self, key: StrKey, inclusive: bool = False) -> Optional[Tuple[StrKey, int]]: ...
    def next_at_or_after(self, key: StrKey) -> Optional[Tuple[StrKey, int]]: ...
    def next_after(self, key: StrKey) -> Optional[Tuple[StrKey, int]]: ...
    def prev(self, key: StrKey, inclusive: bool = False) -> Optional[Tuple[StrKey, int]]: ...
    def prev_at_or_before(self, key: StrKey) -> Optional[Tuple[StrKey, int]]: ...
    def prev_before(self, key: StrKey) -> Optional[Tuple[StrKey, int]]: ...
    def range(
        self,
        start: Optional[StrKey] = None,
        end: Optional[StrKey] = None,
        inclusive: bool = True,
    ) -> List[Tuple[StrKey, int]]: ...
    def items(self) -> List[Tuple[StrKey, int]]: ...
    def keys(self) -> List[StrKey]: ...
    def values(self) -> List[int]: ...
    def update(self, other: Any) -> None: ...
    def __getitem__(self, key: StrKey) -> int: ...
    def __setitem__(self, key: StrKey, val: int) -> None: ...
    def __delitem__(self, key: StrKey) -> None: ...
    def __contains__(self, key: StrKey) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[StrKey]: ...
    def __repr__(self) -> str: ...

class ExpanseBytesMap:
    """Arbitrary byte array-to-integer hash map (JudyHS equivalent)."""

    def __init__(self) -> None: ...
    def insert(self, key: Union[str, bytes], val: int) -> Optional[int]: ...
    @overload
    def get(self, key: Union[str, bytes]) -> Optional[int]: ...
    @overload
    def get(self, key: Union[str, bytes], default: int) -> int: ...
    def get(
        self, key: Union[str, bytes], default: Optional[int] = None
    ) -> Optional[int]: ...
    def remove(self, key: Union[str, bytes]) -> Optional[int]: ...
    @overload
    def pop(self, key: Union[str, bytes]) -> int: ...
    @overload
    def pop(self, key: Union[str, bytes], default: int) -> int: ...
    def pop(
        self, key: Union[str, bytes], default: Optional[int] = None
    ) -> Optional[int]: ...
    def contains_key(self, key: Union[str, bytes]) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    @property
    def empty(self) -> bool: ...
    def mem_used(self) -> int: ...
    def clear(self) -> None: ...
    def items(self) -> Iterator[Tuple[bytes, int]]: ...
    def keys(self) -> Iterator[bytes]: ...
    def values(self) -> Iterator[int]: ...
    def update(self, other: Any) -> None: ...
    def __getitem__(self, key: Union[str, bytes]) -> int: ...
    def __setitem__(self, key: Union[str, bytes], val: int) -> None: ...
    def __delitem__(self, key: Union[str, bytes]) -> None: ...
    def __contains__(self, key: Union[str, bytes]) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[bytes]: ...
    def __repr__(self) -> str: ...

class ExpanseBlobMap:
    """64-bit key-to-byte-payload map with inline packing and arena backing."""

    def __init__(self, chunk_size: Optional[int] = None) -> None: ...
    def insert(self, key: int, data: Union[bytes, bytearray, str], hot_meta: int = 0) -> None: ...
    def get(self, key: int) -> Optional[Tuple[bytes, int]]: ...
    def get_bytes(self, key: int) -> Optional[bytes]: ...
    def remove(self, key: int) -> bool: ...
    def contains_key(self, key: int) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    @property
    def empty(self) -> bool: ...
    def mem_used(self) -> int: ...
    def clear(self) -> None: ...
    def compact(self) -> Tuple[int, int, int, int]: ...
    def scan_filtered(
        self,
        start_key: int,
        end_key: int,
        predicate: Optional[Callable[[int, int], bool]] = None,
        callback: Optional[Callable[[int, bytes, int], bool]] = None,
    ) -> List[Tuple[int, bytes, int]]: ...
    def save_to_file(self, path: str) -> int: ...
    @staticmethod
    def load_from_file(path: str) -> "ExpanseBlobMap": ...
    def __getitem__(self, key: int) -> bytes: ...
    def __setitem__(self, key: int, data: Union[bytes, bytearray, str]) -> None: ...
    def __delitem__(self, key: int) -> None: ...
    def __contains__(self, key: int) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class SyncExpanseSet:
    """Thread-safe optimistic concurrency control (OCC) set with GIL-free reads."""

    def __init__(self) -> None: ...
    def insert(self, key: int) -> bool: ...
    def add(self, key: int) -> bool: ...
    def remove(self, key: int) -> bool: ...
    def discard(self, key: int) -> bool: ...
    def contains(self, key: int) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    @property
    def empty(self) -> bool: ...
    def clear(self) -> None: ...
    def first(self) -> Optional[int]: ...
    def last(self) -> Optional[int]: ...
    def next(self, key: int, inclusive: bool = False) -> Optional[int]: ...
    def prev(self, key: int, inclusive: bool = False) -> Optional[int]: ...
    def count_below(self, key: int) -> int: ...
    def count_range(self, start: int, end: int) -> int: ...
    def by_count(self, index: int) -> Optional[int]: ...
    def range(
        self,
        start: Optional[int] = None,
        end: Optional[int] = None,
        inclusive: bool = True,
    ) -> Iterator[int]: ...
    def update(self, other: Iterable[int]) -> None: ...
    def insert_many(self, keys: Any) -> int: ...
    def __contains__(self, key: int) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    def __repr__(self) -> str: ...

class SyncExpanseMap:
    """Thread-safe optimistic concurrency control (OCC) map with GIL-free reads."""

    def __init__(self) -> None: ...
    def insert(self, key: int, val: int) -> Optional[int]: ...
    @overload
    def get(self, key: int) -> Optional[int]: ...
    @overload
    def get(self, key: int, default: int) -> int: ...
    def get(self, key: int, default: Optional[int] = None) -> Optional[int]: ...
    def remove(self, key: int) -> Optional[int]: ...
    @overload
    def pop(self, key: int) -> int: ...
    @overload
    def pop(self, key: int, default: int) -> int: ...
    def pop(self, key: int, default: Optional[int] = None) -> Optional[int]: ...
    def contains_key(self, key: int) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    @property
    def empty(self) -> bool: ...
    def clear(self) -> None: ...
    def first(self) -> Optional[Tuple[int, int]]: ...
    def last(self) -> Optional[Tuple[int, int]]: ...
    def next(self, key: int, inclusive: bool = False) -> Optional[Tuple[int, int]]: ...
    def prev(self, key: int, inclusive: bool = False) -> Optional[Tuple[int, int]]: ...
    def count_below(self, key: int) -> int: ...
    def count_range(self, start: int, end: int) -> int: ...
    def by_count(self, index: int) -> Optional[Tuple[int, int]]: ...
    def range(
        self,
        start: Optional[int] = None,
        end: Optional[int] = None,
        inclusive: bool = True,
    ) -> Iterator[Tuple[int, int]]: ...
    def keys(self) -> Iterator[int]: ...
    def values(self) -> Iterator[int]: ...
    def items(self) -> Iterator[Tuple[int, int]]: ...
    def update(self, other: Any) -> None: ...
    def insert_many(self, keys: Any, values: Any) -> int: ...
    def __getitem__(self, key: int) -> int: ...
    def __setitem__(self, key: int, val: int) -> None: ...
    def __delitem__(self, key: int) -> None: ...
    def __contains__(self, key: int) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    def __repr__(self) -> str: ...
