#!/usr/bin/env python3
"""
scripts/check_bench_shapes.py

Asserts that all timed benchmark and example harnesses declare a machine-readable
workload shape (# Workload shape table) in their module doc comments, and generates
the canonical harness audit tables in docs/BENCHMARKING.md.

Usage:
    python3 scripts/check_bench_shapes.py             # Check all harnesses and docs/BENCHMARKING.md
    python3 scripts/check_bench_shapes.py --check     # Same as above (exits non-zero on mismatch/error)
    python3 scripts/check_bench_shapes.py --write     # Updates docs/BENCHMARKING.md in place
    python3 scripts/check_bench_shapes.py --self-test # Runs unit self-tests (fail-then-pass)
"""

from __future__ import annotations

import argparse
import json
import glob
import os
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

REQUIRED_FIELDS = [
    "workload_id",
    "group",
    "population",
    "probes_and_reuse",
    "hit_rate",
    "miss_gen_method",
    "value_dereference",
    "measured_region",
    "arm_symmetry",
    "statistics",
    "verdict",
]

GROUP_TITLES = {
    1: "Group 1: C-API Benches & Examples (`crates/expanse-capi/`)",
    2: "Group 2: Core Point/Batch Lookup & Micro-Benches (`crates/expanse/benches/`)",
    3: "Group 3: Hashbrown Comparison Suite (`crates/expanse/benches/`)",
    4: "Group 4: Workloads & Domain Suites (`crates/expanse/benches/`)",
    5: "Group 5: Standalone Examples & Profile Drivers (`crates/expanse/examples/`)",
}

BEGIN_MARKER = "<!-- BEGIN HARNESS AUDIT TABLE (generated by scripts/check_bench_shapes.py --write) -->"
END_MARKER = "<!-- END HARNESS AUDIT TABLE -->"


def get_repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def is_timed_harness(source: str) -> bool:
    """Classifies whether a Rust file is a timed benchmark/example harness or a helper module."""
    return bool(re.search(r"\b(criterion_group!|criterion_main!|main!|fn\s+main\b)", source))


def discover_harnesses(repo_root: Path) -> Tuple[List[Path], List[Path]]:
    """Discovers Rust source files under benches and examples directories across all crates.
    Returns (timed_harnesses, helper_modules)."""
    capi_benches = glob.glob(str(repo_root / "crates" / "expanse-capi" / "benches" / "*.rs"))
    capi_examples = glob.glob(str(repo_root / "crates" / "expanse-capi" / "examples" / "*.rs"))
    core_benches = glob.glob(str(repo_root / "crates" / "expanse" / "benches" / "**" / "*.rs"), recursive=True)
    core_examples = glob.glob(str(repo_root / "crates" / "expanse" / "examples" / "*.rs"))
    
    all_files = sorted(
        [
            Path(p)
            for p in (capi_benches + capi_examples + core_benches + core_examples)
            if not p.endswith(".disabled")
        ]
    )

    timed = []
    helpers = []
    for path in all_files:
        try:
            content = path.read_text(encoding="utf-8")
        except Exception as e:
            print(f"Error reading {path}: {e}", file=sys.stderr)
            continue
        if is_timed_harness(content):
            timed.append(path)
        else:
            helpers.append(path)

    return timed, helpers


def parse_workload_shape(source: str, filename: str) -> Tuple[Optional[Dict[str, str]], List[str]]:
    """Parses the //! # Workload shape table from the module doc comments.
    Returns (shape_dict, list_of_errors)."""
    errors = []
    
    # Extract leading module doc comment lines
    doc_lines = []
    for line in source.splitlines():
        trimmed = line.strip()
        if trimmed.startswith("//!"):
            doc_lines.append(trimmed[3:].strip())
        elif trimmed.startswith("//") or trimmed == "":
            continue
        else:
            # First non-comment, non-empty line marks end of module doc
            break

    doc_text = "\n".join(doc_lines)
    # Find the section starting at '# Workload shape' up to the next markdown header or end
    section_match = re.search(r"#+\s+Workload shape\b(.*?)(?=\n#+ |\Z)", doc_text, re.DOTALL | re.IGNORECASE)
    if not section_match:
        errors.append(f"{filename}: Missing '# Workload shape' markdown table in module doc comments (//!)")
        return None, errors

    section_text = section_match.group(1)
    shape_match = re.search(r"((?:\|[^\n]+\n?)+)", section_text)
    if not shape_match:
        errors.append(f"{filename}: Missing markdown table (| Property | Value |) under '# Workload shape'")
        return None, errors

    table_block = shape_match.group(1)
    props: Dict[str, str] = {}
    
    for row in table_block.strip().splitlines():
        cells = [c.strip() for c in row.split("|")]
        # cells: ['', prop, val, '']
        if len(cells) >= 4:
            k = cells[1].strip("` ").strip()
            v = cells[2].strip()
            if k and k != "---" and k.lower() != "property":
                if k in ("workload_id", "group"):
                    v = v.strip("` ").strip()
                props[k] = v

    # Validate required fields
    for field in REQUIRED_FIELDS:
        if field not in props:
            errors.append(f"{filename}: Missing required property '{field}' in '# Workload shape' table")
        elif not props[field]:
            errors.append(f"{filename}: Empty value for property '{field}' in '# Workload shape' table")

    if "group" in props:
        try:
            grp = int(props["group"])
            if grp not in GROUP_TITLES:
                errors.append(f"{filename}: Invalid group '{props['group']}', expected integer 1..5")
        except ValueError:
            errors.append(f"{filename}: Group '{props['group']}' is not a valid integer")

    return props, errors


def generate_audit_tables(harness_data: List[Tuple[str, Dict[str, str]]]) -> str:
    """Generates the markdown audit tables for Groups 1 to 5."""
    # Organize by group
    grouped: Dict[int, List[Tuple[str, Dict[str, str]]]] = {g: [] for g in range(1, 6)}
    for relpath, shape in harness_data:
        grp = int(shape["group"])
        grouped[grp].append((relpath, shape))

    lines = []
    for grp in range(1, 6):
        title = GROUP_TITLES[grp]
        lines.append(f"### {title}\n")
        lines.append("| File | Population ($N$) | Probes & Reuse | Hit Rate | Miss Gen Method | Value Dereference | Measured Region | Arm Symmetry | Statistics | Verdict & Notes |")
        lines.append("|---|---|---|---|---|---|---|---|---|---|")
        for relpath, shape in grouped[grp]:
            file_link = f"[`{relpath}`](../{relpath})"
            pop = shape.get("population", "")
            probes = shape.get("probes_and_reuse", "")
            hit = shape.get("hit_rate", "")
            miss = shape.get("miss_gen_method", "")
            deref = shape.get("value_dereference", "")
            region = shape.get("measured_region", "")
            arm = shape.get("arm_symmetry", "")
            stats = shape.get("statistics", "")
            verdict = shape.get("verdict", "")
            lines.append(f"| {file_link} | {pop} | {probes} | {hit} | {miss} | {deref} | {region} | {arm} | {stats} | {verdict} |")
        if grp < 5:
            lines.append("\n---\n")

    return "\n".join(lines)


# Fields that discriminate one workload from another when a number is read out
# of context. Population and probe cardinality are what made the 366x mismatch
# in #453 invisible; hit rate and dereference are what made two "lookup" arms
# non-comparable. Emitted beside every published figure so a reader does not
# have to open the harness (#487 item A).
DISCRIMINATING_FIELDS = [
    "population",
    "probes_and_reuse",
    "hit_rate",
    "value_dereference",
]


def collect_shapes(repo_root: Path) -> Dict[str, Dict[str, str]]:
    """`{workload_id -> shape}` for every timed harness that declares one.

    Each entry carries `source` (repo-relative path) and `stem` (the file stem)
    on top of the declared fields. `stem` is the join key reports use:
    iai-callgrind names a bench `<target>::<group>::<bench>`, and the target is
    the harness file stem, so `search_instructions` resolves to
    `benches/search_instructions.rs` and thence to `domain_search_instructions`.

    Parse failures are skipped rather than raised — `--check` is the gate that
    fails on them, and a report should not die because a declaration regressed.
    """
    timed_paths, _ = discover_harnesses(repo_root)
    shapes: Dict[str, Dict[str, str]] = {}
    for path in timed_paths:
        relpath = str(path.relative_to(repo_root))
        shape, errs = parse_workload_shape(path.read_text(encoding="utf-8"), relpath)
        if shape is None or errs:
            continue
        wid = shape.get("workload_id")
        if not wid:
            continue
        entry = dict(shape)
        entry["source"] = relpath
        entry["stem"] = path.stem
        shapes[wid] = entry
    return shapes


def shapes_by_stem(repo_root: Path) -> Dict[str, Dict[str, str]]:
    """`{file stem -> shape}` for stems that identify exactly one harness.

    Stems shared by more than one harness are **excluded**, not arbitrarily
    resolved: `crates/expanse/benches/smoke_instructions.rs` and
    `crates/expanse-capi/benches/smoke_instructions.rs` both produce the bench
    target `smoke_instructions`, so a report row naming it could be either.
    Attaching one of the two shapes would state a population and hit rate the
    number may not have, which is the failure this whole mechanism exists to
    prevent. Ambiguous stems come back from `ambiguous_stems` instead, for the
    caller to report as ambiguous rather than as declared or missing.
    """
    grouped = ambiguous_stems(repo_root)
    return {
        v["stem"]: v
        for v in collect_shapes(repo_root).values()
        if v["stem"] not in grouped
    }


def ambiguous_stems(repo_root: Path) -> Dict[str, List[str]]:
    """`{file stem -> [workload ids]}` for stems shared by several harnesses."""
    seen: Dict[str, List[str]] = {}
    for wid, sh in collect_shapes(repo_root).items():
        seen.setdefault(sh["stem"], []).append(wid)
    return {k: sorted(v) for k, v in seen.items() if len(v) > 1}


def summarize_shape(shape: Dict[str, str]) -> str:
    """One-line rendering of the discriminating fields, for report inlining."""
    parts = [f"{f.replace('_', ' ')} {shape[f]}" for f in DISCRIMINATING_FIELDS if shape.get(f)]
    return " · ".join(parts)


def check_and_generate(repo_root: Path, write: bool = False) -> int:
    timed_paths, helper_paths = discover_harnesses(repo_root)
    print(f"check_bench_shapes.py: {len(timed_paths)} timed harnesses, {len(helper_paths)} helper modules found")

    all_errors = []
    seen_workload_ids: Dict[str, str] = {}
    harness_data: List[Tuple[str, Dict[str, str]]] = []

    for path in timed_paths:
        relpath = str(path.relative_to(repo_root))
        source = path.read_text(encoding="utf-8")
        shape, errs = parse_workload_shape(source, relpath)
        if errs:
            all_errors.extend(errs)
        if shape:
            wid = shape.get("workload_id")
            if wid:
                if wid in seen_workload_ids:
                    all_errors.append(f"Duplicate workload_id '{wid}' in {relpath} (previously seen in {seen_workload_ids[wid]})")
                else:
                    seen_workload_ids[wid] = relpath
            harness_data.append((relpath, shape))

    if all_errors:
        print("\n".join(f"ERROR: {e}" for e in all_errors), file=sys.stderr)
        return 1

    generated_tables = generate_audit_tables(harness_data)

    benchmarking_doc = repo_root / "docs" / "BENCHMARKING.md"
    if not benchmarking_doc.exists():
        print(f"ERROR: {benchmarking_doc} does not exist", file=sys.stderr)
        return 1

    doc_content = benchmarking_doc.read_text(encoding="utf-8")
    
    pattern = re.escape(BEGIN_MARKER) + r"(.*?)" + re.escape(END_MARKER)
    match = re.search(pattern, doc_content, re.DOTALL)
    if not match:
        print(f"ERROR: Demarcation markers not found in {benchmarking_doc}.\nExpected '{BEGIN_MARKER}' and '{END_MARKER}'", file=sys.stderr)
        return 1

    existing_section = match.group(1).strip()
    desired_section = generated_tables.strip()

    if write:
        new_content = doc_content[:match.start()] + BEGIN_MARKER + "\n\n" + desired_section + "\n\n" + END_MARKER + doc_content[match.end():]
        benchmarking_doc.write_text(new_content, encoding="utf-8")
        print(f"check_bench_shapes.py: Updated {benchmarking_doc}")
        return 0
    else:
        if existing_section != desired_section:
            print(f"ERROR: {benchmarking_doc} audit table is out of date. Run 'python3 scripts/check_bench_shapes.py --write' to sync.", file=sys.stderr)
            return 1
        print("check_bench_shapes.py: All 35 harness shapes valid and docs/BENCHMARKING.md is in sync.")
        return 0


def run_self_tests() -> int:
    """Fail-then-pass unit self-tests for classifier, parser, required fields, and table generation."""
    print("Running check_bench_shapes.py unit self-tests...")

    # 1. Classifier test
    sample_timed = "fn main() { println!(\"hello\"); }"
    sample_bench = "criterion_group!(benches, bench_fn); criterion_main!(benches);"
    sample_helper = "pub fn helper_fn() -> u64 { 42 }"
    assert is_timed_harness(sample_timed) is True, "sample_timed should classify as timed"
    assert is_timed_harness(sample_bench) is True, "sample_bench should classify as timed"
    assert is_timed_harness(sample_helper) is False, "sample_helper should classify as helper"

    # 2. Valid shape parsing
    valid_doc = """//! Headline description.
//!
//! # Workload shape
//!
//! | Property | Value |
//! |---|---|
//! | `workload_id` | `test_workload` |
//! | `group` | 1 |
//! | `population` | 10k |
//! | `probes_and_reuse` | 10k, reuse 1.0 |
//! | `hit_rate` | 100% |
//! | `miss_gen_method` | None |
//! | `value_dereference` | `sink ^= *slot` |
//! | `measured_region` | Clean |
//! | `arm_symmetry` | Symmetric |
//! | `statistics` | Exact |
//! | `verdict` | **PASS** |

fn main() {}
"""
    shape, errs = parse_workload_shape(valid_doc, "test.rs")
    assert not errs, f"Expected no errors for valid doc, got: {errs}"
    assert shape is not None and shape["workload_id"] == "test_workload"
    assert shape["group"] == "1"

    # 3. Fail-then-pass test for all 11 required fields
    for field in REQUIRED_FIELDS:
        # Create invalid doc omitting this field
        lines = []
        for l in valid_doc.splitlines():
            if f"`{field}`" not in l:
                lines.append(l)
        bad_doc = "\n".join(lines)
        bad_shape, bad_errs = parse_workload_shape(bad_doc, "bad.rs")
        assert any(f"Missing required property '{field}'" in e for e in bad_errs), f"Expected missing '{field}' error, got {bad_errs}"

    # 4. Invalid group test
    bad_grp_doc = valid_doc.replace("| `group` | 1 |", "| `group` | 99 |")
    _, grp_errs = parse_workload_shape(bad_grp_doc, "bad_grp.rs")
    assert any("Invalid group '99'" in e for e in grp_errs), f"Expected invalid group error, got {grp_errs}"

    # 5. Missing workload shape header test
    no_header_doc = "//! Just a doc without table\nfn main() {}"
    _, no_hdr_errs = parse_workload_shape(no_header_doc, "no_hdr.rs")
    assert any("Missing '# Workload shape'" in e for e in no_hdr_errs), f"Expected missing header error, got {no_hdr_errs}"

    # 6. Table generation test
    test_data = [
        ("crates/expanse/benches/test.rs", {
            "workload_id": "test_workload",
            "group": "1",
            "population": "10k",
            "probes_and_reuse": "10k",
            "hit_rate": "100%",
            "miss_gen_method": "None",
            "value_dereference": "deref",
            "measured_region": "Clean",
            "arm_symmetry": "Symmetric",
            "statistics": "Exact",
            "verdict": "**PASS**",
        })
    ]
    tables = generate_audit_tables(test_data)
    assert "### Group 1: C-API Benches & Examples (`crates/expanse-capi/`)" in tables
    assert "[`crates/expanse/benches/test.rs`](../crates/expanse/benches/test.rs)" in tables

    # 7. Emit mode: shapes are joinable by file stem and summarise to one line,
    #    so reports can print a number's shape beside it (#487).
    shapes = collect_shapes(get_repo_root())
    assert shapes, "no workload shapes collected"
    by_stem = shapes_by_stem(get_repo_root())
    assert "search_instructions" in by_stem, sorted(by_stem)[:5]
    assert by_stem["search_instructions"]["workload_id"] == "domain_search_instructions"
    # Every collected entry carries the join key and its source.
    for wid, sh in shapes.items():
        assert sh.get("stem"), f"{wid} has no stem"
        assert sh.get("source", "").endswith(".rs"), f"{wid} has no source path"
    # A stem shared by two harnesses is excluded from the join, never resolved
    # to one of them: core and capi both ship benches/smoke_instructions.rs.
    ambiguous = ambiguous_stems(get_repo_root())
    assert "smoke_instructions" in ambiguous, ambiguous
    assert ambiguous["smoke_instructions"] == ["capi_smoke_instructions", "core_smoke_instructions"]
    assert "smoke_instructions" not in by_stem, "ambiguous stem must not resolve to one harness"
    assert len(by_stem) == len(shapes) - sum(len(v) for v in ambiguous.values())
    summary = summarize_shape(shapes["capi_bench_vs_libjudy"])
    assert "population" in summary and "hit rate" in summary, summary
    # fail-then-pass: a shape missing every discriminating field summarises to
    # nothing rather than to a fabricated description.
    assert summarize_shape({"workload_id": "x"}) == ""

    print("ALL 7 SELF-TESTS PASSED.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Check benchmark workload shape declarations and sync audit table.")
    parser.add_argument("--check", action="store_true", help="Check declarations and audit table sync (default)")
    parser.add_argument("--write", action="store_true", help="Write generated audit table to docs/BENCHMARKING.md")
    parser.add_argument("--self-test", action="store_true", help="Run unit self-tests")
    parser.add_argument("--json", action="store_true", help="Emit {workload_id: shape} as JSON for report joining")
    args = parser.parse_args()

    if args.self_test:
        return run_self_tests()

    repo_root = get_repo_root()
    if args.json:
        json.dump(collect_shapes(repo_root), sys.stdout, indent=2, sort_keys=True)
        sys.stdout.write("\n")
        return 0

    return check_and_generate(repo_root, write=args.write)


if __name__ == "__main__":
    sys.exit(main())
