#!/usr/bin/env python3
"""Markdown for the counter cells `bench_counters.py` collected (#737).

The issue's constraint: the README gains its counters "from a generator, never
typed by hand" (AGENTS.md section 8.2, and section 8.9 principle 5 — the raw
event row divided by the exact probe count, verbatim, with its interval). This
renders `counters_*.json` and nothing else.

    python3 scripts/counter_tables.py                # every cell found
    python3 scripts/counter_tables.py --pair a b     # a ratio table between two cells

The pair mode exists because a per-process count cannot separate the two arms
inside one cell, but two cells that differ in exactly one thing — the insertion
order token — bracket that one thing with both arms present in both. The ratio
column is what that difference costs; it is not an attribution to either arm.
"""

from __future__ import annotations

import argparse
import glob
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

EVENT_LABEL = {
    "page-faults": "page-faults",
    "dTLB-load-misses": "dTLB-load-misses",
    "LLC-load-misses": "LLC-load-misses",
    "cycles": "cycles",
    "instructions": "instructions",
    "mem_load_l3_hit_retired.xsnp_hitm": "xsnp_hitm",
}


def load_all() -> list[dict]:
    out = []
    for f in sorted(glob.glob(str(REPO_ROOT / "docs/benchmarks/*/results/counters_*.json"))):
        out.append(json.loads(Path(f).read_text()))
    return out


def fmt(v: float | None) -> str:
    if v is None:
        return "—"
    if v >= 100:
        return f"{v:,.0f}"
    if v >= 1:
        return f"{v:.3g}"
    return f"{v:.4g}"


def cell_rows(d: dict) -> str:
    prov = d["provenance"]
    out = [f"**`{d['cell']}`** — `{d['binary']} {' '.join(d['args'])}`, #{d['issue']}; "
           f"{d['repeats']} repeats, {d['ops_per_repeat']:,} operations per repeat "
           f"({d['rounds_per_repeat']} rounds), PMU `{prov['pmu']}` pinned to "
           f"`{prov['pmu_cpus']}`.\n",
           "| event | per operation | BCa 95% |", "|---|---:|---|"]
    for ev, v in d["events"].items():
        if v["per_op_mean"] is None:
            continue
        ci = ("—" if v["ci_lower"] is None
              else f"[{fmt(v['ci_lower'])}, {fmt(v['ci_upper'])}]")
        out.append(f"| `{EVENT_LABEL.get(ev, ev)}` | {fmt(v['per_op_mean'])} | {ci} |")
    out.append("")
    return "\n".join(out)


def pair_table(a: dict, b: dict) -> str:
    """Two cells side by side, with the ratio of their per-operation figures."""
    out = [f"| event | `{a['cell']}` | `{b['cell']}` | ratio |", "|---|---:|---:|---:|"]
    for ev in a["events"]:
        va = a["events"][ev]["per_op_mean"]
        vb = b["events"].get(ev, {}).get("per_op_mean")
        if va is None or vb is None:
            continue
        r = "—" if not va else f"{vb / va:.2f}×"
        out.append(f"| `{EVENT_LABEL.get(ev, ev)}` | {fmt(va)} | {fmt(vb)} | **{r}** |")
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pair", nargs=2, metavar=("BASE", "OTHER"))
    args = ap.parse_args()

    cells = load_all()
    if not cells:
        print("no counters_*.json found; run scripts/bench_counters.py first",
              file=sys.stderr)
        return 1
    by_name = {c["cell"]: c for c in cells}

    if args.pair:
        a, b = args.pair
        for n in (a, b):
            if n not in by_name:
                print(f"unknown cell {n}", file=sys.stderr)
                return 1
        prov = by_name[a]["provenance"]
        print(f"<!-- generated by scripts/counter_tables.py from counters_*.json "
              f"at commit {prov['commit']} -->\n")
        print(pair_table(by_name[a], by_name[b]))
        return 0

    prov = cells[0]["provenance"]
    print(f"<!-- generated by scripts/counter_tables.py from counters_*.json "
          f"at commit {prov['commit']} -->\n")
    print(f"`perf stat` on the reference host, PMU `{prov['pmu']}`, workload pinned to "
          f"`{prov['pmu_cpus']}`, `perf_event_paranoid` = {prov['perf_event_paranoid']}. "
          f"Each figure is the raw event row divided by the harness's own operation "
          f"count, with a BCa 95% bootstrap interval over the repeats.\n")
    print(f"> **Scope.** {prov['scope']}\n>\n> **Attribution.** {prov['attribution']}\n")
    for c in cells:
        print(cell_rows(c))
    return 0


if __name__ == "__main__":
    sys.exit(main())
