"""Type stubs for expanse-trie Python bindings."""

from typing import (
    Any,
    Callable,
    Dict,
    Iterable,
    Iterator,
    List,
    Optional,
    Sequence,
    Tuple,
    Union,
    overload,
)

__version__: str

class ExpanseSet:
    """Sparse, dynamic 64-bit integer set (Judy1 equivalent)."""

    def __init__(self, iterable: Optional[Iterable[int]] = None) -> None: ...
    def insert(self, key: int) -> bool: ...
    def add(self, key: int) -> None: ...
    def remove(self, key: int) -> bool: ...
    def discard(self, key: int) -> bool: ...
    def contains(self, key: int) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def mem_used(self) -> int: ...
    def total_node_allocs(self) -> int: ...
    def clear(self) -> None: ...
    def first(self) -> Optional[int]: ...
    def last(self) -> Optional[int]: ...
    def next_at_or_after(self, key: int) -> Optional[int]: ...
    def next_after(self, key: int) -> Optional[int]: ...
    def prev_at_or_before(self, key: int) -> Optional[int]: ...
    def prev_before(self, key: int) -> Optional[int]: ...
    def count_below(self, key: int) -> int: ...
    def count_range(self, start: int, end: int) -> int: ...
    def by_count(self, n: int) -> Optional[int]: ...
    def range(self, start: Optional[int] = None, end: Optional[int] = None) -> List[int]: ...
    def to_list(self) -> List[int]: ...
    def __contains__(self, key: int) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    def __repr__(self) -> str: ...

class ExpanseMap:
    """Sparse, dynamic 64-bit integer-to-integer map (JudyL equivalent)."""

    def __init__(
        self, items: Optional[Union[Dict[int, int], Iterable[Tuple[int, int]]]] = None
    ) -> None: ...
    def insert(self, key: int, val: int) -> Optional[int]: ...
    @overload
    def get(self, key: int) -> Optional[int]: ...
    @overload
    def get(self, key: int, default: int) -> int: ...
    def get(self, key: int, default: Optional[int] = None) -> Optional[int]: ...
    def remove(self, key: int) -> Optional[int]: ...
    @overload
    def pop(self, key: int) -> int: ...
    @overload
    def pop(self, key: int, default: int) -> int: ...
    def pop(self, key: int, default: Optional[int] = None) -> Optional[int]: ...
    def contains_key(self, key: int) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def mem_used(self) -> int: ...
    def total_node_allocs(self) -> int: ...
    def clear(self) -> None: ...
    def first(self) -> Optional[Tuple[int, int]]: ...
    def last(self) -> Optional[Tuple[int, int]]: ...
    def next_at_or_after(self, key: int) -> Optional[Tuple[int, int]]: ...
    def next_after(self, key: int) -> Optional[Tuple[int, int]]: ...
    def prev_at_or_before(self, key: int) -> Optional[Tuple[int, int]]: ...
    def prev_before(self, key: int) -> Optional[Tuple[int, int]]: ...
    def count_below(self, key: int) -> int: ...
    def count_range(self, start: int, end: int) -> int: ...
    def by_count(self, n: int) -> Optional[Tuple[int, int]]: ...
    def range(
        self, start: Optional[int] = None, end: Optional[int] = None
    ) -> List[Tuple[int, int]]: ...
    def keys(self) -> List[int]: ...
    def values(self) -> List[int]: ...
    def items(self) -> List[Tuple[int, int]]: ...
    def __getitem__(self, key: int) -> int: ...
    def __setitem__(self, key: int, val: int) -> None: ...
    def __delitem__(self, key: int) -> None: ...
    def __contains__(self, key: int) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    def __repr__(self) -> str: ...

class ExpanseStrMap:
    """Variable-length string/bytes-to-integer trie map (JudySL equivalent)."""

    def __init__(self) -> None: ...
    def insert(self, key: Union[str, bytes], val: int) -> Optional[int]: ...
    @overload
    def get(self, key: Union[str, bytes]) -> Optional[int]: ...
    @overload
    def get(self, key: Union[str, bytes], default: int) -> int: ...
    def get(
        self, key: Union[str, bytes], default: Optional[int] = None
    ) -> Optional[int]: ...
    def remove(self, key: Union[str, bytes]) -> Optional[int]: ...
    def contains_key(self, key: Union[str, bytes]) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def mem_used(self) -> int: ...
    def clear(self) -> int: ...
    def first(self) -> Optional[Tuple[Union[str, bytes], int]]: ...
    def last(self) -> Optional[Tuple[Union[str, bytes], int]]: ...
    def next_at_or_after(
        self, key: Union[str, bytes]
    ) -> Optional[Tuple[Union[str, bytes], int]]: ...
    def next_after(
        self, key: Union[str, bytes]
    ) -> Optional[Tuple[Union[str, bytes], int]]: ...
    def prev_at_or_before(
        self, key: Union[str, bytes]
    ) -> Optional[Tuple[Union[str, bytes], int]]: ...
    def prev_before(
        self, key: Union[str, bytes]
    ) -> Optional[Tuple[Union[str, bytes], int]]: ...
    def range(
        self,
        start: Optional[Union[str, bytes]] = None,
        end: Optional[Union[str, bytes]] = None,
    ) -> List[Tuple[Union[str, bytes], int]]: ...
    def items(self) -> List[Tuple[Union[str, bytes], int]]: ...
    def keys(self) -> List[Union[str, bytes]]: ...
    def values(self) -> List[int]: ...
    def __getitem__(self, key: Union[str, bytes]) -> int: ...
    def __setitem__(self, key: Union[str, bytes], val: int) -> None: ...
    def __delitem__(self, key: Union[str, bytes]) -> None: ...
    def __contains__(self, key: Union[str, bytes]) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class ExpanseBytesMap:
    """Arbitrary byte array-to-integer hash map (JudyHS equivalent)."""

    def __init__(self) -> None: ...
    def insert(self, key: Union[str, bytes], val: int) -> Optional[int]: ...
    @overload
    def get(self, key: Union[str, bytes]) -> Optional[int]: ...
    @overload
    def get(self, key: Union[str, bytes], default: int) -> int: ...
    def get(
        self, key: Union[str, bytes], default: Optional[int] = None
    ) -> Optional[int]: ...
    def remove(self, key: Union[str, bytes]) -> Optional[int]: ...
    def contains_key(self, key: Union[str, bytes]) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def mem_used(self) -> int: ...
    def clear(self) -> None: ...
    def items(self) -> List[Tuple[Union[str, bytes], int]]: ...
    def keys(self) -> List[Union[str, bytes]]: ...
    def values(self) -> List[int]: ...
    def __getitem__(self, key: Union[str, bytes]) -> int: ...
    def __setitem__(self, key: Union[str, bytes], val: int) -> None: ...
    def __delitem__(self, key: Union[str, bytes]) -> None: ...
    def __contains__(self, key: Union[str, bytes]) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class SyncExpanseSet:
    """Thread-safe optimistic concurrency control (OCC) Set with GIL-free reads."""

    def __init__(self, iterable: Optional[Iterable[int]] = None) -> None: ...
    def insert(self, key: int) -> bool: ...
    def add(self, key: int) -> None: ...
    def remove(self, key: int) -> bool: ...
    def discard(self, key: int) -> bool: ...
    def contains(self, key: int) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __contains__(self, key: int) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class SyncExpanseMap:
    """Thread-safe optimistic concurrency control (OCC) Map with GIL-free reads."""

    def __init__(
        self, items: Optional[Union[Dict[int, int], Iterable[Tuple[int, int]]]] = None
    ) -> None: ...
    def insert(self, key: int, val: int) -> Optional[int]: ...
    def remove(self, key: int) -> Optional[int]: ...
    @overload
    def get(self, key: int) -> Optional[int]: ...
    @overload
    def get(self, key: int, default: int) -> int: ...
    def get(self, key: int, default: Optional[int] = None) -> Optional[int]: ...
    def contains_key(self, key: int) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __getitem__(self, key: int) -> int: ...
    def __setitem__(self, key: int, val: int) -> None: ...
    def __delitem__(self, key: int) -> None: ...
    def __contains__(self, key: int) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
